openapi: 3.0.0
info:
  title: User Authentication API
  description: REST API for user registration, login, logout, and profile access
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: API docs
paths:
  /api/v1/registration:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: gaurav_singh
                email:
                  type: string
                  format: email
                  example: gaurav_singh@gmail.com
                password:
                  type: string
                  minLength: 6
                  example: gaurav_singh_123
              required:
                - username
                - email
                - password
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
        '400':
          description: Incorrect inputs
        '409':
          description: Email/username already taken or Incorrect inputs
        '500':
          description: Internal Server Error
          
  /api/v1/login:
    post:
      summary: Login with username or email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: gaurav_singh
                password:
                  type: string
                  example: gaurav_singh_123
              required:
                - (username | email)
                - password
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
        '400':
          description: Incorrect inputs
        '401':
          description: Invalid username or password
        '404':
          description: User not found
        '500':
          description: Internal Server Error

  /api/v1/logout:
    post:
      summary: Logout the user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout successfully!
        '500':
          description: Internal Server Error
          
  /api/v1/profile:
    post:
      summary: Get user profile
      security:
        - BearerAuth: []
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      username:
                        type: string
                        example: gaurav_singh
                      email:
                        type: string
                        format: email
                        example: gaurav_singh@gmail.com
                  message:
                    type: string
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '500':
          description: Internal Server Error
security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
